#!/bin/bash
BASEDIR=$(pwd);

# Disable basic AOSP packages
cd $BASEDIR/build;
git apply $BASEDIR/patches/build.diff;

# Disable basic LineageOS packages
cd $BASEDIR/vendor/lineage;
git apply $BASEDIR/patches/vendor_lineage.diff;

# Apply notch fixes for daisy
cd $BASEDIR/framework/base/packages/SystemUI/src/com/android/systemui/statusbar;
git apply $BASEDIR/patches/notch.diff;
