#!/bin/bash
BASEDIR=$(pwd);

# Disable basic AOSP packages
echo "Applying build"
cd $BASEDIR/build;
patch -p1 < $BASEDIR/patches/build.diff;

# Disable basic LineageOS packages
echo "Applying vendor_lineage"
cd $BASEDIR/vendor/lineage;
patch -p1 < $BASEDIR/patches/vendor_lineage.diff;

# Apply notch fixes for daisy
echo "Applying notch fixes"
cd $BASEDIR/frameworks/base/packages/SystemUI/src/com/android/systemui/statusbar;
patch -p1 < $BASEDIR/patches/notch.diff;

# Apply restricted signature spoofing patch
echo "Applying signature spoofing"
cd $BASEDIR/frameworks/base;
patch -p1 < $BASEDIR/patches/signature.diff;
